require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckId:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/WhereExists:
  Enabled: true
