 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users/courses", type: :request do
  subject { FactoryBot.build(:course) }

  # Users::Course. As you add validations to Users::Course, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: Faker::Name.unique.name,
      start_datetime: Faker::Date.between(from: '2020-08-21', to: '2020-08-25'),
      end_datetime: Faker::Date.between(from: '2020-09-21', to: '2020-09-25'),
      length_of_students: Faker::Number.decimal_part(digits: 2),
      user_id: FactoryBot.create(:user).id
    }
  end

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      byebug
      Course.create! valid_attributes
      get users_courses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      course = Course.create! valid_attributes
      get users_course_url(users_course)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_users_course_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      course = Course.create! valid_attributes
      get edit_users_course_url(users_course)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Users::Course" do
        expect {
          post users_courses_url, params: { users_course: valid_attributes }
        }.to change(Course, :count).by(1)
      end

      it "redirects to the created users_course" do
        post users_courses_url, params: { users_course: valid_attributes }
        expect(response).to redirect_to(users_course_url(@users_course))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Users::Course" do
        expect {
          post users_courses_url, params: { users_course: invalid_attributes }
        }.to change(Course, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post users_courses_url, params: { users_course: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested users_course" do
        course = Course.create! valid_attributes
        patch users_course_url(users_course), params: { users_course: new_attributes }
        course.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the users_course" do
        course = Course.create! valid_attributes
        patch users_course_url(users_course), params: { users_course: new_attributes }
        course.reload
        expect(response).to redirect_to(users_course_url(course))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        course = Course.create! valid_attributes
        patch users_course_url(users_course), params: { users_course: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested users_course" do
      course = Course.create! valid_attributes
      expect {
        delete users_course_url(users_course)
      }.to change(Course, :count).by(-1)
    end

    it "redirects to the users_courses list" do
      course = Course.create! valid_attributes
      delete users_course_url(users_course)
      expect(response).to redirect_to(users_courses_url)
    end
  end
end
