require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/users/enrollments', type: :request do
  # Users::Enrollment. As you add validations to Users::Enrollment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Users::Enrollment.create! valid_attributes
      get users_enrollments_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      enrollment = Users::Enrollment.create! valid_attributes
      get users_enrollment_url(users_enrollment)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_users_enrollment_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      enrollment = Users::Enrollment.create! valid_attributes
      get edit_users_enrollment_url(users_enrollment)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Users::Enrollment' do
        expect do
          post users_enrollments_url, params: { users_enrollment: valid_attributes }
        end.to change(Users::Enrollment, :count).by(1)
      end

      it 'redirects to the created users_enrollment' do
        post users_enrollments_url, params: { users_enrollment: valid_attributes }
        expect(response).to redirect_to(users_enrollment_url(@users_enrollment))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Users::Enrollment' do
        expect do
          post users_enrollments_url, params: { users_enrollment: invalid_attributes }
        end.to change(Users::Enrollment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post users_enrollments_url, params: { users_enrollment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested users_enrollment' do
        enrollment = Users::Enrollment.create! valid_attributes
        patch users_enrollment_url(users_enrollment), params: { users_enrollment: new_attributes }
        enrollment.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the users_enrollment' do
        enrollment = Users::Enrollment.create! valid_attributes
        patch users_enrollment_url(users_enrollment), params: { users_enrollment: new_attributes }
        enrollment.reload
        expect(response).to redirect_to(users_enrollment_url(enrollment))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        enrollment = Users::Enrollment.create! valid_attributes
        patch users_enrollment_url(users_enrollment), params: { users_enrollment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested users_enrollment' do
      enrollment = Users::Enrollment.create! valid_attributes
      expect do
        delete users_enrollment_url(users_enrollment)
      end.to change(Users::Enrollment, :count).by(-1)
    end

    it 'redirects to the users_enrollments list' do
      enrollment = Users::Enrollment.create! valid_attributes
      delete users_enrollment_url(users_enrollment)
      expect(response).to redirect_to(users_enrollments_url)
    end
  end
end
