require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/teachers/courses', type: :request do
  # Teachers::Course. As you add validations to Teachers::Course, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Teachers::Course.create! valid_attributes
      get teachers_courses_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      course = Teachers::Course.create! valid_attributes
      get teachers_course_url(teachers_course)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_teachers_course_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      course = Teachers::Course.create! valid_attributes
      get edit_teachers_course_url(teachers_course)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Teachers::Course' do
        expect do
          post teachers_courses_url, params: { teachers_course: valid_attributes }
        end.to change(Teachers::Course, :count).by(1)
      end

      it 'redirects to the created teachers_course' do
        post teachers_courses_url, params: { teachers_course: valid_attributes }
        expect(response).to redirect_to(teachers_course_url(@teachers_course))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Teachers::Course' do
        expect do
          post teachers_courses_url, params: { teachers_course: invalid_attributes }
        end.to change(Teachers::Course, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post teachers_courses_url, params: { teachers_course: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested teachers_course' do
        course = Teachers::Course.create! valid_attributes
        patch teachers_course_url(teachers_course), params: { teachers_course: new_attributes }
        course.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the teachers_course' do
        course = Teachers::Course.create! valid_attributes
        patch teachers_course_url(teachers_course), params: { teachers_course: new_attributes }
        course.reload
        expect(response).to redirect_to(teachers_course_url(course))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        course = Teachers::Course.create! valid_attributes
        patch teachers_course_url(teachers_course), params: { teachers_course: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested teachers_course' do
      course = Teachers::Course.create! valid_attributes
      expect do
        delete teachers_course_url(teachers_course)
      end.to change(Teachers::Course, :count).by(-1)
    end

    it 'redirects to the teachers_courses list' do
      course = Teachers::Course.create! valid_attributes
      delete teachers_course_url(teachers_course)
      expect(response).to redirect_to(teachers_courses_url)
    end
  end
end
